# Generated by Django 3.0.2 on 2020-01-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunder', '0004_auto_20200117_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
