# Generated by Django 3.0.2 on 2020-01-19 20:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kunder', '0005_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_populated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='even',
            new_name='week_0',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='odd',
            new_name='week_1',
        ),
        migrations.CreateModel(
            name='DeliveryReciver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Bara siffror, utan mellanslag')])),
                ('city', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kunder.Customer')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunder.Delivery')),
            ],
        ),
    ]
