# Generated by Django 3.0.2 on 2020-01-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kunder', '0006_auto_20200119_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zip',
            new_name='postal_code',
        ),
    ]
