# Generated by Django 3.0.2 on 2020-01-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kunder', '0007_auto_20200119_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cancels',
            field=models.ManyToManyField(related_name='canceled_customers', to='kunder.Delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryreciver',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='kunder.Delivery'),
        ),
    ]
