# Generated by Django 3.0.2 on 2020-01-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunder', '0008_auto_20200120_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='1@1.com', max_length=255, unique=True, verbose_name='e-post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='cancels',
            field=models.ManyToManyField(blank=True, related_name='canceled_customers', to='kunder.Delivery'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True, verbose_name='e-post'),
        ),
    ]
