# Generated by Django 3.0.2 on 2020-01-26 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kunder', '0010_auto_20200126_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
    ]
