# Generated by Django 3.0.2 on 2020-01-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunder', '0011_auto_20200126_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='week_0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='week_1',
            field=models.BooleanField(default=True),
        ),
    ]
